In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import scipy.stats as stats
import warnings 
warnings.filterwarnings('ignore')

# Import Data

In [2]:
loan=pd.read_csv(r'C:\Users\Deepika\Downloads\PYTHON\LoansData.csv')
loan

Amount.Requested  Amount.Funded.By.Investors Interest.Rate Loan.Length  \
0              20000.0                    20000.00         8.90%   36 months   
1              19200.0                    19200.00        12.12%   36 months   
2              35000.0                    35000.00        21.98%   60 months   
3              10000.0                     9975.00         9.99%   36 months   
4              12000.0                    12000.00        11.71%   36 months   
...                ...                         ...           ...         ...   
2495           30000.0                    29950.00        16.77%   60 months   
2496           16000.0                    16000.00        14.09%   60 months   
2497           10000.0                    10000.00        13.99%   36 months   
2498            6000.0                     6000.00        12.42%   36 months   
2499            9000.0                     5242.75        13.79%   36 months   

            Loan.Purpose Debt.To.Income.Ratio State Home.Ownership  \
0     debt_consolidation               14.90%    SC       MORTGAGE   
1     debt_consolidation               28.36%    TX       MORTGAGE   
2     debt_consolidation               23.81%    CA       MORTGAGE   
3     debt_consolidation               14.30%    KS       MORTGAGE   
4            credit_card               18.78%    NJ           RENT   
...                  ...                  ...   ...            ...   
2495  debt_consolidation               19.23%    NY       MORTGAGE   
2496    home_improvement               21.54%    MD            OWN   
2497  debt_consolidation                4.89%    PA       MORTGAGE   
2498      major_purchase               16.66%    NJ           RENT   
2499  debt_consolidation                6.76%    NY           RENT   

      Monthly.Income FICO.Range  Open.CREDIT.Lines  Revolving.CREDIT.Balance  \
0            6541.67    735-739               14.0                   14272.0   
1            4583.33    715-719               12.0                   11140.0   
2           11500.00    690-694               14.0                   21977.0   
3            3833.33    695-699               10.0                    9346.0   
4            3195.00    695-699               11.0                   14469.0   
...              ...        ...                ...                       ...   
2495         9250.00    705-709               15.0                   45880.0   
2496         8903.25    740-744               18.0                   18898.0   
2497         2166.67    680-684                4.0                    4544.0   
2498         3500.00    675-679                8.0                    7753.0   
2499         3875.00    670-674                7.0                    7589.0   

      Inquiries.in.the.Last.6.Months Employment.Length  
0                                2.0          < 1 year  
1                                1.0           2 years  
2                                1.0           2 years  
3                                0.0           5 years  
4                                0.0           9 years  
...                              ...               ...  
2495                             1.0           8 years  
2496                             1.0         10+ years  
2497                             0.0         10+ years  
2498                             0.0           5 years  
2499                             0.0         10+ years  

[2500 rows x 14 columns]

# Data Audit

In [3]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Amount.Requested                2499 non-null   float64
 1   Amount.Funded.By.Investors      2499 non-null   float64
 2   Interest.Rate                   2498 non-null   object 
 3   Loan.Length                     2500 non-null   object 
 4   Loan.Purpose                    2500 non-null   object 
 5   Debt.To.Income.Ratio            2499 non-null   object 
 6   State                           2500 non-null   object 
 7   Home.Ownership                  2499 non-null   object 
 8   Monthly.Income                  2499 non-null   float64
 9   FICO.Range                      2498 non-null   object 
 10  Open.CREDIT.Lines               2497 non-null   float64
 11  Revolving.CREDIT.Balance        2497 non-null   float64
 12  Inquiries.in.the.Last.6.Months  24

In [4]:
loan.dtypes

Amount.Requested                  float64
Amount.Funded.By.Investors        float64
Interest.Rate                      object
Loan.Length                        object
Loan.Purpose                       object
Debt.To.Income.Ratio               object
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                 float64
Revolving.CREDIT.Balance          float64
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
dtype: object

In [5]:
loan.isna().sum()

Amount.Requested                   1
Amount.Funded.By.Investors         1
Interest.Rate                      2
Loan.Length                        0
Loan.Purpose                       0
Debt.To.Income.Ratio               1
State                              0
Home.Ownership                     1
Monthly.Income                     1
FICO.Range                         2
Open.CREDIT.Lines                  3
Revolving.CREDIT.Balance           3
Inquiries.in.the.Last.6.Months     3
Employment.Length                 77
dtype: int64

# Data Cleaning

In [6]:
loan.rename({'Amount.Requested':'Amount_Requested','Amount.Funded.By.Investors':'Amount_Funded_By_Investors','Interest.Rate':'Interest_Rate','Loan.Length':'Loan_Length','Loan.Purpose':'Loan_Purpose'
            ,'Loan.Purpose':'Loan_Purpose','Debt.To.Income.Ratio':'Debt_To_income_Ratio','Home.Ownership':'Home_Ownership'
            ,'Monthly.Income':'Monthly_Income','FICO.Range':'FICO_Range','Open.CREDIT.Lines':'Open_CREDIT_Lines',
            'Revolving.CREDIT.Balance':'Revolving_CREDIT_Balance','Inquiries.in.the.Last.6.Months':'Inquiries_in_the_Last_6_Months',
            'Employment.Length':'Employment_Length'},axis="columns",inplace=True)

In [7]:
loan.columns

Index(['Amount_Requested', 'Amount_Funded_By_Investors', 'Interest_Rate',
       'Loan_Length', 'Loan_Purpose', 'Debt_To_income_Ratio', 'State',
       'Home_Ownership', 'Monthly_Income', 'FICO_Range', 'Open_CREDIT_Lines',
       'Revolving_CREDIT_Balance', 'Inquiries_in_the_Last_6_Months',
       'Employment_Length'],
      dtype='object')

In [8]:
loan["Interest_Rate"]=pd.to_numeric(loan["Interest_Rate"].str.replace("%",""))

In [9]:
loan["Loan_Length"]=pd.to_numeric(loan["Loan_Length"].str.replace("months",""))

In [10]:
loan["Debt_To_income_Ratio"]=pd.to_numeric(loan["Debt_To_income_Ratio"].str.replace("%",""))

In [11]:
loan.dtypes

Amount_Requested                  float64
Amount_Funded_By_Investors        float64
Interest_Rate                     float64
Loan_Length                         int64
Loan_Purpose                       object
Debt_To_income_Ratio              float64
State                              object
Home_Ownership                     object
Monthly_Income                    float64
FICO_Range                         object
Open_CREDIT_Lines                 float64
Revolving_CREDIT_Balance          float64
Inquiries_in_the_Last_6_Months    float64
Employment_Length                  object
dtype: object

In [12]:
loan=loan.dropna()

# Statistical Analysis

In [13]:
#obtaining samples
x=loan["Amount_Funded_By_Investors"]
y=loan["Interest_Rate"]

In [14]:
stats.ttest_ind(x,y)

Ttest_indResult(statistic=76.66587325965071, pvalue=0.0)

Conculsion

In [15]:
x=loan["Interest_Rate"]
y=loan["Loan_Length"]

In [16]:
stats.ttest_ind(x,y)

Ttest_indResult(statistic=-128.36728199919077, pvalue=0.0)

Conculsion

In [17]:
grp1=loan.loc[(loan["Loan_Purpose"]=='debt_consolidation')]['Interest_Rate']
grp2=loan.loc[(loan["Loan_Purpose"]=='credit_card')]['Interest_Rate']
grp3=loan.loc[(loan["Loan_Purpose"]=='other')]['Interest_Rate']
grp4=loan.loc[(loan["Loan_Purpose"]=='moving')]['Interest_Rate']
grp5=loan.loc[(loan["Loan_Purpose"]=='car')]['Interest_Rate']
grp6=loan.loc[(loan["Loan_Purpose"]=='vacation')]['Interest_Rate']
grp7=loan.loc[(loan["Loan_Purpose"]=='home_improvement')]['Interest_Rate']
grp8=loan.loc[(loan["Loan_Purpose"]=='house')]['Interest_Rate']
grp9=loan.loc[(loan["Loan_Purpose"]=='major_purchase')]['Interest_Rate']
grp10=loan.loc[(loan["Loan_Purpose"]=='educational')]['Interest_Rate']
grp11=loan.loc[(loan["Loan_Purpose"]=='medical')]['Interest_Rate']
grp12=loan.loc[(loan["Loan_Purpose"]=='wedding')]['Interest_Rate']
grp13=loan.loc[(loan["Loan_Purpose"]=='small_business')]['Interest_Rate']
grp14=loan.loc[(loan["Loan_Purpose"]=='renewable_energy')]['Interest_Rate']



In [18]:
stats.f_oneway(grp1,grp2,grp3,grp4,grp5,grp6,grp7,grp8,grp9,grp10,grp11,grp12,grp13,grp14)

F_onewayResult(statistic=7.330838185919651, pvalue=2.7646672581411367e-14)

Conculsion

In [19]:
# obtaining cross tables
cross_tb=pd.crosstab(loan["Home_Ownership"],loan["FICO_Range"],margins=True)
cross_tb

FICO_Range      640-644  645-649  650-654  655-659  660-664  665-669  670-674  \
Home_Ownership                                                                  
MORTGAGE              0        1        1        0       40       52       66   
OTHER                 0        0        0        1        0        0        1   
OWN                   1        0        0        0       14       17       13   
RENT                  4        2        0        3       64       69       87   
All                   5        3        1        4      118      138      167   

FICO_Range      675-679  680-684  685-689  ...  785-789  790-794  795-799  \
Home_Ownership                             ...                              
MORTGAGE             78       55       58  ...       12       15        7   
OTHER                 1        2        0  ...        0        0        0   
OWN                  10        9       10  ...        1        1        1   
RENT                 72       91       60  ...        4        4        5   
All                 161      157      128  ...       17       20       13   

FICO_Range      800-804  805-809  810-814  815-819  820-824  830-834   All  
Home_Ownership                                                              
MORTGAGE              7        6        5        5        0        1  1109  
OTHER                 0        0        0        0        0        0     5  
OWN                   3        2        1        0        1        0   189  
RENT                  2        3        2        0        0        0  1110  
All                  12       11        8        5        1        1  2413  

[5 rows x 39 columns]

In [20]:
stats.chi2_contingency(cross_tb)

(269.78812027573343,
 1.3041014985760768e-08,
 152,
 array([[2.29796933e+00, 1.37878160e+00, 4.59593867e-01, 1.83837547e+00,
         5.42320763e+01, 6.34239536e+01, 7.67521757e+01, 7.39946125e+01,
         7.21562370e+01, 5.88280149e+01, 6.20451720e+01, 6.71007045e+01,
         5.69896395e+01, 6.02067965e+01, 4.91765437e+01, 4.22826357e+01,
         4.96361376e+01, 4.18230419e+01, 4.32018235e+01, 2.98736013e+01,
         2.29796933e+01, 2.48180688e+01, 2.75756320e+01, 2.02221301e+01,
         2.06817240e+01, 1.47070037e+01, 7.81309573e+00, 1.01110651e+01,
         1.19494405e+01, 7.81309573e+00, 9.19187733e+00, 5.97472027e+00,
         5.51512640e+00, 5.05553253e+00, 3.67675093e+00, 2.29796933e+00,
         4.59593867e-01, 4.59593867e-01, 1.10900000e+03],
        [1.03605470e-02, 6.21632822e-03, 2.07210941e-03, 8.28843763e-03,
         2.44508910e-01, 2.85951098e-01, 3.46042271e-01, 3.33609615e-01,
         3.25321177e-01, 2.65230004e-01, 2.79734770e-01, 3.02527973e-01,
         2.569

Conculsion

# Import Data

In [21]:
p_quotes=pd.read_csv(r'C:\Users\Deepika\Downloads\PYTHON\Price_Quotes.csv')
p_quotes

Order_Number  Barry_Price  Mary_Price
0              1          126         114
1              2          110         118
2              3          138         114
3              4          142         111
4              5          146         129
5              6          136         119
6              7           94          97
7              8          103         104
8              9          140         127
9             10          152         133
10            11          108         103
11            12           97         108

# Data Audit

In [22]:
p_quotes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_Number  12 non-null     int64
 1   Barry_Price   12 non-null     int64
 2   Mary_Price    12 non-null     int64
dtypes: int64(3)
memory usage: 416.0 bytes


In [23]:
p_quotes.dtypes

Order_Number    int64
Barry_Price     int64
Mary_Price      int64
dtype: object

In [24]:
p_quotes.isna().sum()

Order_Number    0
Barry_Price     0
Mary_Price      0
dtype: int64

# Statistical Analysis

In [25]:
#obtaining Samples
avg_Barry_price_quotes=p_quotes.groupby(by=['Order_Number'])[['Barry_Price']].mean()
avg_Mary_price_quotes=p_quotes.groupby(by=['Order_Number'])[['Mary_Price']].mean()


In [26]:
stats.ttest_ind(avg_Barry_price_quotes,avg_Mary_price_quotes)

Ttest_indResult(statistic=array([1.41474367]), pvalue=array([0.17114226]))

Conculsion

# Import Data

In [27]:
treat_fac=pd.read_csv(r'C:\Users\Deepika\Downloads\PYTHON\Treatment_Facility.csv')
treat_fac

Month Reengineer  Employee_Turnover       VAR4        VAR5
0       1      Prior             0.0000  24.390244   42.682927
1       2      Prior             6.0606  19.354839   25.806452
2       3      Prior            12.1212  35.087719  146.198830
3       4      Prior             3.3333  18.404908  110.429448
4       5      Prior            12.9032  17.964072   23.952096
5       6      Prior             9.6774  41.176471   47.058824
6       7      Prior            11.7647  13.422819    0.000000
7       8      Prior            11.4286  31.250000   25.000000
8       9      Prior            23.0769  17.241379  132.183908
9      10      Prior            15.0000  16.574586   16.574586
10     11      Prior            10.0000   5.917160   88.757396
11     12      Prior            26.0870  21.164021   31.746032
12     13      Prior            11.1111   5.076142   10.152284
13     14       Post            26.6667   9.708738   29.126214
14     15       Post            17.9487   4.201681   21.008403
15     16       Post            12.8205  13.043478   34.782609
16     17       Post            15.7895   9.950249   19.900498
17     18       Post             0.0000   9.950249    9.950249
18     19       Post            30.7692   8.510638   25.531915
19     20       Post            26.8293   9.259259   23.148148

# Data Audit

In [28]:
treat_fac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Month              20 non-null     int64  
 1   Reengineer         20 non-null     object 
 2   Employee_Turnover  20 non-null     float64
 3   VAR4               20 non-null     float64
 4   VAR5               20 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 928.0+ bytes


In [29]:
treat_fac.dtypes

Month                  int64
Reengineer            object
Employee_Turnover    float64
VAR4                 float64
VAR5                 float64
dtype: object

In [30]:
treat_fac.isna().sum()

Month                0
Reengineer           0
Employee_Turnover    0
VAR4                 0
VAR5                 0
dtype: int64

# Statistical Analysis

In [31]:
#obtaining samples
grp1=treat_fac.loc[(treat_fac.Reengineer=="Prior")][['VAR5']]
grp2=treat_fac.loc[(treat_fac.Reengineer=="Post")][['VAR5']]


In [32]:
stats.f_oneway(grp1,grp2)

F_onewayResult(statistic=array([2.65010538]), pvalue=array([0.12091989]))

Conculsion

# Import Data

In [33]:
priority=pd.read_csv(r'C:\Users\Deepika\Downloads\PYTHON\Priority_Assessment.csv')
priority

Days Priority
0     3.3     High
1     7.9   Medium
2     0.3     High
3     0.7   Medium
4     8.6   Medium
..    ...      ...
637   2.5      Low
638   0.3     High
639   0.3   Medium
640   1.3   Medium
641   0.5     High

[642 rows x 2 columns]

# Data Audit

In [34]:
priority.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642 entries, 0 to 641
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Days      642 non-null    float64
 1   Priority  642 non-null    object 
dtypes: float64(1), object(1)
memory usage: 10.2+ KB


In [35]:
priority.dtypes

Days        float64
Priority     object
dtype: object

In [36]:
priority.isna().sum()

Days        0
Priority    0
dtype: int64

# Statistical Analysis

In [37]:
#obtaining samples
grp1=priority.loc[(priority.Priority=="High")][['Days']]
grp2=priority.loc[(priority.Priority=="Medium")][['Days']]
grp3=priority.loc[(priority.Priority=="Low")][['Days']]


In [38]:
stats.f_oneway(grp1,grp2,grp3)

F_onewayResult(statistic=array([1.81231101]), pvalue=array([0.16411459]))

Conculsion

# Import Data 

In [39]:
film=pd.read_csv(r'C:\Users\Deepika\Downloads\PYTHON\Films.csv')
film

_rowstate_                    Movie  Gender Marital_Status  Sinage  \
0             0  Ferris Buellers Day Off  Female        Married     2.0   
1             0  Ferris Buellers Day Off  Female         Single     1.0   
2             0  Ferris Buellers Day Off    Male        Married     2.0   
3             0  Ferris Buellers Day Off  Female        Married     1.0   
4             0  Ferris Buellers Day Off  Female        Married     1.0   
..          ...                      ...     ...            ...     ...   
325           0               Old School       2              2     1.0   
326           0               Old School       1              1     2.0   
327           0               Old School       2              1     2.0   
328           0               Old School       1              1     1.0   
329           0               Old School       2              2     2.0   

     Parking  Clean  Overall  Age  Income Hear_About  
0        2.0    2.0      2.0  3.0     1.0          5  
1        1.0    1.0      1.0  2.0     1.0          5  
2        4.0    3.0      2.0  4.0     1.0          5  
3        3.0    2.0      2.0  4.0     1.0          5  
4        1.0    1.0      1.0  3.0     3.0          1  
..       ...    ...      ...  ...     ...        ...  
325      2.0    1.0      1.0  2.0     1.0          1  
326      2.0    2.0      2.0  3.0     3.0          5  
327      1.0    1.0      2.0  2.0     2.0          5  
328      1.0    1.0      1.0  2.0     1.0          3  
329      2.0    3.0      1.0  2.0     1.0          5  

[330 rows x 11 columns]

# Data Audit

In [40]:
film.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   _rowstate_      330 non-null    int64  
 1   Movie           330 non-null    object 
 2   Gender          330 non-null    object 
 3   Marital_Status  328 non-null    object 
 4   Sinage          328 non-null    float64
 5   Parking         328 non-null    float64
 6   Clean           327 non-null    float64
 7   Overall         328 non-null    float64
 8   Age             328 non-null    float64
 9   Income          314 non-null    float64
 10  Hear_About      323 non-null    object 
dtypes: float64(6), int64(1), object(4)
memory usage: 28.5+ KB


In [41]:
film.dtypes

_rowstate_          int64
Movie              object
Gender             object
Marital_Status     object
Sinage            float64
Parking           float64
Clean             float64
Overall           float64
Age               float64
Income            float64
Hear_About         object
dtype: object

In [42]:
film.isna().sum()

_rowstate_         0
Movie              0
Gender             0
Marital_Status     2
Sinage             2
Parking            2
Clean              3
Overall            2
Age                2
Income            16
Hear_About         7
dtype: int64

# Data Cleaning

In [43]:
film=film.dropna()
film

_rowstate_                    Movie  Gender Marital_Status  Sinage  \
0             0  Ferris Buellers Day Off  Female        Married     2.0   
1             0  Ferris Buellers Day Off  Female         Single     1.0   
2             0  Ferris Buellers Day Off    Male        Married     2.0   
3             0  Ferris Buellers Day Off  Female        Married     1.0   
4             0  Ferris Buellers Day Off  Female        Married     1.0   
..          ...                      ...     ...            ...     ...   
325           0               Old School       2              2     1.0   
326           0               Old School       1              1     2.0   
327           0               Old School       2              1     2.0   
328           0               Old School       1              1     1.0   
329           0               Old School       2              2     2.0   

     Parking  Clean  Overall  Age  Income Hear_About  
0        2.0    2.0      2.0  3.0     1.0          5  
1        1.0    1.0      1.0  2.0     1.0          5  
2        4.0    3.0      2.0  4.0     1.0          5  
3        3.0    2.0      2.0  4.0     1.0          5  
4        1.0    1.0      1.0  3.0     3.0          1  
..       ...    ...      ...  ...     ...        ...  
325      2.0    1.0      1.0  2.0     1.0          1  
326      2.0    2.0      2.0  3.0     3.0          5  
327      1.0    1.0      2.0  2.0     2.0          5  
328      1.0    1.0      1.0  2.0     1.0          3  
329      2.0    3.0      1.0  2.0     1.0          5  

[301 rows x 11 columns]

In [44]:
def gender (x):
    if x.Gender == 'Male' :
        return '1'
    elif x.Gender == 'Female'  :
        return '2'
    elif x.Gender == '1'  :
        return '1'
    else :
        return '2'

In [45]:
#converting males to 1 and females to 2 
film.Gender = film.apply(gender, axis=1)

In [46]:
def married_status (x):
    if x.Marital_Status == 'Married' :
        return '1'
    elif x.Marital_Status == 'Single'  :
        return '2'
    elif x.Marital_Status == '1'  :
        return '1'
    else :
        return '2'

In [47]:
#converting married to 1 and singles to 2
film.Marital_Status = film.apply(married_status, axis=1)

In [48]:
film

_rowstate_                    Movie Gender Marital_Status  Sinage  \
0             0  Ferris Buellers Day Off      2              1     2.0   
1             0  Ferris Buellers Day Off      2              2     1.0   
2             0  Ferris Buellers Day Off      1              1     2.0   
3             0  Ferris Buellers Day Off      2              1     1.0   
4             0  Ferris Buellers Day Off      2              1     1.0   
..          ...                      ...    ...            ...     ...   
325           0               Old School      2              2     1.0   
326           0               Old School      1              1     2.0   
327           0               Old School      2              1     2.0   
328           0               Old School      1              1     1.0   
329           0               Old School      2              2     2.0   

     Parking  Clean  Overall  Age  Income Hear_About  
0        2.0    2.0      2.0  3.0     1.0          5  
1        1.0    1.0      1.0  2.0     1.0          5  
2        4.0    3.0      2.0  4.0     1.0          5  
3        3.0    2.0      2.0  4.0     1.0          5  
4        1.0    1.0      1.0  3.0     3.0          1  
..       ...    ...      ...  ...     ...        ...  
325      2.0    1.0      1.0  2.0     1.0          1  
326      2.0    2.0      2.0  3.0     3.0          5  
327      1.0    1.0      2.0  2.0     2.0          5  
328      1.0    1.0      1.0  2.0     1.0          3  
329      2.0    3.0      1.0  2.0     1.0          5  

[301 rows x 11 columns]

# Statistical Analysis`

In [49]:
# Finding Mean,Standard Deviation and Standard Error to know the Confidence Intervals

mean=film.Overall.mean()
length=len(film)
SD=film.Overall.std()
SE=SD/np.sqrt(length)
print(mean,length,SD,SE)

1.6212624584717608 301 0.6753367561589327 0.038925763497347034


In [50]:
#for 95% Confidence Level

L=mean-(1.96*SE)
U=mean+(1.96*SE)
print(L,U)

1.5449679620169605 1.697556954926561


Conclusion

In [51]:
# data prep for chi square test
obs = pd.crosstab( film.Sinage,film.Overall )

# Ho: No relationship, independant
# H1: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# with increase in sinage rating overall staifaction is also increases

(121.32462033201084,
 3.054444776360607e-18,
 16,
 array([[4.77906977e+01, 5.16279070e+01, 4.18604651e+00, 3.48837209e-01,
         1.04651163e+00],
        [6.37209302e+01, 6.88372093e+01, 5.58139535e+00, 4.65116279e-01,
         1.39534884e+00],
        [2.04817276e+01, 2.21262458e+01, 1.79401993e+00, 1.49501661e-01,
         4.48504983e-01],
        [2.73089701e+00, 2.95016611e+00, 2.39202658e-01, 1.99335548e-02,
         5.98006645e-02],
        [2.27574751e+00, 2.45847176e+00, 1.99335548e-01, 1.66112957e-02,
         4.98338870e-02]]))

Conclusion

In [52]:
# data prep for chi square test
obs = pd.crosstab( film.Parking,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# with increase in parking rating overall staifaction is also increases

(218.79348282085004,
 1.2264032549812005e-37,
 16,
 array([[5.55282392e+01, 5.99867110e+01, 4.86378738e+00, 4.05315615e-01,
         1.21594684e+00],
        [6.32657807e+01, 6.83455150e+01, 5.54152824e+00, 4.61794020e-01,
         1.38538206e+00],
        [1.31993355e+01, 1.42591362e+01, 1.15614618e+00, 9.63455150e-02,
         2.89036545e-01],
        [3.18604651e+00, 3.44186047e+00, 2.79069767e-01, 2.32558140e-02,
         6.97674419e-02],
        [1.82059801e+00, 1.96677741e+00, 1.59468439e-01, 1.32890365e-02,
         3.98671096e-02]]))

Conclusion

In [53]:
# data prep for chi square test
obs = pd.crosstab( film.Clean,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# with increase in clean rating overall staifaction is also increases

(129.0342392337068,
 9.882317099745693e-20,
 16,
 array([[6.09900332e+01, 6.58870432e+01, 5.34219269e+00, 4.45182724e-01,
         1.33554817e+00],
        [6.28106312e+01, 6.78538206e+01, 5.50166113e+00, 4.58471761e-01,
         1.37541528e+00],
        [1.00132890e+01, 1.08172757e+01, 8.77076412e-01, 7.30897010e-02,
         2.19269103e-01],
        [2.27574751e+00, 2.45847176e+00, 1.99335548e-01, 1.66112957e-02,
         4.98338870e-02],
        [9.10299003e-01, 9.83388704e-01, 7.97342193e-02, 6.64451827e-03,
         1.99335548e-02]]))

Conclusion

In [54]:
# data prep for chi square test
obs = pd.crosstab( film.Gender,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# overall staifaction is depending on Gender

(3.520985228074472,
 0.4746946769990794,
 4,
 array([[48.24584718, 52.11960133,  4.22591362,  0.35215947,  1.05647841],
        [88.75415282, 95.88039867,  7.77408638,  0.64784053,  1.94352159]]))

Conclusion

In [55]:
# data prep for chi square test
obs = pd.crosstab( film.Marital_Status,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# overall staifaction is depending on Martial Status

(4.716918153414504,
 0.3175954690113918,
 4,
 array([[ 41.41860465,  44.74418605,   3.62790698,   0.30232558,
           0.90697674],
        [ 95.58139535, 103.25581395,   8.37209302,   0.69767442,
           2.09302326]]))

Conclusion

In [56]:
# data prep for chi square test
obs = pd.crosstab( film.Age,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# overall staifaction is depending on Age

(11.024837235069565,
 0.5267913370930692,
 12,
 array([[1.00132890e+01, 1.08172757e+01, 8.77076412e-01, 7.30897010e-02,
         2.19269103e-01],
        [7.46445183e+01, 8.06378738e+01, 6.53820598e+00, 5.44850498e-01,
         1.63455150e+00],
        [4.91561462e+01, 5.31029900e+01, 4.30564784e+00, 3.58803987e-01,
         1.07641196e+00],
        [3.18604651e+00, 3.44186047e+00, 2.79069767e-01, 2.32558140e-02,
         6.97674419e-02]]))

Conclusion

In [57]:
# data prep for chi square test
obs = pd.crosstab( film.Income,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# overall staifaction is depending on Income

(4.9478735426424,
 0.7631326888324932,
 8,
 array([[61.44518272, 66.37873754,  5.3820598 ,  0.44850498,  1.34551495],
        [36.41196013, 39.33554817,  3.18936877,  0.26578073,  0.79734219],
        [39.14285714, 42.28571429,  3.42857143,  0.28571429,  0.85714286]]))

Conclusion

In [58]:
# data prep for chi square test
obs = pd.crosstab( film.Hear_About,film.Overall )

# Ho: No relationship, independant
# Ha: variables are related, dependant
   
# CI: 95%
# p: 0.05
  

# perform the test

stats.chi2_contingency( obs )

# business conclusion
# overall staifaction is depending on Gender

(21.659744148982803,
 0.9920532791201511,
 40,
 array([[8.64784053e+00, 9.34219269e+00, 7.57475083e-01, 6.31229236e-02,
         1.89368771e-01],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [5.00664452e+00, 5.40863787e+00, 4.38538206e-01, 3.65448505e-02,
         1.09634551e-01],
        [9.10299003e-01, 9.83388704e-01, 7.97342193e-02, 6.64451827e-03,
         1.99335548e-02],
        [5.91694352e+00, 6.39202658e+00, 5.18272425e-01, 4.31893688e-02,
         1.29568106e-01],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [1.77508306e+01, 1.91760797e+01, 1.55481728e+00, 1.29568106e-01,
         3.88704319e-01],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [9.64916944e+01, 1.04239203e+02, 8.45182724e+00, 7.043

Conclusion

# Final Conclusion

In [59]:
# Demography on Gender
gender = film.groupby('Gender')[['Gender']].count()
gender = gender.rename( columns={'Gender': 'count'}).reset_index()
gender['Prob'] = gender['count'] / gender['count'].sum()
print(gender)
print('  AS Gender 2 is Female and 1 is male. That means their is 64% probability audiance is female')

  Gender  count      Prob
0      1    106  0.352159
1      2    195  0.647841
  AS Gender 2 is Female and 1 is male. That means their is 64% probability audiance is female


In [60]:
#Demography on Martial Status
Marital_Status = film.groupby('Marital_Status')[['Marital_Status']].count()
Marital_Status = Marital_Status.rename( columns={'Marital_Status': 'count'}).reset_index()
Marital_Status['Prob'] = Marital_Status['count'] / Marital_Status['count'].sum()
print(Marital_Status)
print('  Their is 69% probability that the audiance is Single')

  Marital_Status  count      Prob
0              1     91  0.302326
1              2    210  0.697674
  Their is 69% probability that the audiance is Single


In [61]:
#Demography on Age
Age = film.groupby('Age')[['Age']].count()
Age = Age.rename( columns={'Age': 'count'}).reset_index()
Age['Prob'] = Age['count'] / Age['count'].sum()
print(Age)
print('  Their is 54% probability that the age of the audiance is between 13-30')

   Age  count      Prob
0  1.0     22  0.073090
1  2.0    164  0.544850
2  3.0    108  0.358804
3  4.0      7  0.023256
  Their is 54% probability that the age of the audiance is between 13-30


In [62]:
#Demography on Income
Income = film.groupby('Income')[['Income']].count()
Income = Income.rename( columns={'Income': 'count'}).reset_index()
Income['Prob'] = Income['count'] / Income['count'].sum()
print(Income)
print('  Their is 44% probability that the Income of the audiance is less than 50K')

   Income  count      Prob
0     1.0    135  0.448505
1     2.0     80  0.265781
2     3.0     86  0.285714
  Their is 44% probability that the Income of the audiance is less than 50K


In [63]:
Hear_About = film.groupby('Hear_About')[['Hear_About']].count()
Hear_About = Hear_About.rename( columns={'Hear_About': 'count'}).reset_index()
Hear_About['Prob'] = Hear_About['count'] / Hear_About['count'].sum()
print(Hear_About.sort_values(by='Prob', ascending = False))
print('  Their is 70% probability that the audiance heard about the film series solely through word of mouth.')

   Hear_About  count      Prob
9           5    212  0.704319
7           4     39  0.129568
0           1     19  0.063123
4           3     13  0.043189
2           2     11  0.036545
3         2,5      2  0.006645
1         1,5      1  0.003322
5         3,4      1  0.003322
6         3,5      1  0.003322
8         4,5      1  0.003322
10        5,4      1  0.003322
  Their is 70% probability that the audiance heard about the film series solely through word of mouth.
